-- Replace Superpowers (obra) skills with Compound Engineering (EveryInc) skills

-- 1. Remove Superpowers skills
DELETE FROM public.skills
WHERE id IN (
  'seed_writing-plans',
  'seed_brainstorming',
  'seed_subagent-driven-development',
  'seed_systematic-debugging',
  'seed_using-git-worktrees',
  'seed_test-driven-development',
  'seed_verification-before-completion'
);

-- 2. Insert Compound Engineering skills
INSERT INTO public.skills (
  id,
  title_da,
  title_en,
  category,
  vibe_coder,
  vibe_coder_title_da,
  vibe_coder_title_en,
  rating,
  reviews_count,
  description_da,
  description_en,
  tags,
  github_url,
  is_danish,
  denmark_specific,
  upvotes,
  slug,
  review_state
) VALUES
  (
    'seed_ce-brainstorm',
    'ce-brainstorm',
    'ce-brainstorm',
    'agent-methodology',
    'EveryInc',
    'Every Inc.',
    'Every Inc.',
    5.0,
    0,
    'Afdækker krav og tekniske valg gennem struktureret dialog og genererer en præcis kravspecifikation til den efterfølgende planlægning.',
    'Explore requirements and approaches through collaborative dialogue, then write a right-sized requirements document.',
    ARRAY['claude-code', 'compound-engineering', 'brainstorming', 'requirements'],
    'https://github.com/EveryInc/compound-engineering-plugin/tree/main/plugins/compound-engineering/skills/ce-brainstorm',
    false,
    false,
    1,
    'ce-brainstorm',
    'approved'
  ),
  (
    'seed_ce-plan',
    'ce-plan',
    'ce-plan',
    'agent-methodology',
    'EveryInc',
    'Every Inc.',
    'Every Inc.',
    5.0,
    0,
    'Udarbejder detaljerede implementeringsplaner for komplekse opgaver med trinvis nedbrydning, afhængighedssporing og subagent-review.',
    'Create structured implementation plans for multi-step tasks with dependency tracking and subagent review.',
    ARRAY['claude-code', 'compound-engineering', 'planning', 'architecture'],
    'https://github.com/EveryInc/compound-engineering-plugin/tree/main/plugins/compound-engineering/skills/ce-plan',
    false,
    false,
    1,
    'ce-plan',
    'approved'
  ),
  (
    'seed_ce-work',
    'ce-work',
    'ce-work',
    'agent-methodology',
    'EveryInc',
    'Every Inc.',
    'Every Inc.',
    5.0,
    0,
    'Eksekverer tekniske implementeringsplaner trin for trin med automatisk kvalitetssikring, testkørsler og færdiggørelse af features.',
    'Execute work efficiently while maintaining quality, isolating tasks, and finishing complete features.',
    ARRAY['claude-code', 'compound-engineering', 'workflow', 'execution'],
    'https://github.com/EveryInc/compound-engineering-plugin/tree/main/plugins/compound-engineering/skills/ce-work',
    false,
    false,
    1,
    'ce-work',
    'approved'
  ),
  (
    'seed_ce-compound',
    'ce-compound',
    'ce-compound',
    'agent-methodology',
    'EveryInc',
    'Every Inc.',
    'Every Inc.',
    5.0,
    0,
    'Opsummerer og fastholder løsninger på komplekse problemer som genanvendelig viden og mønstre direkte i projektets kodebase.',
    'Document recently solved problems to compound your team''s knowledge and project domain vocabulary.',
    ARRAY['claude-code', 'compound-engineering', 'knowledge', 'learning'],
    'https://github.com/EveryInc/compound-engineering-plugin/tree/main/plugins/compound-engineering/skills/ce-compound',
    false,
    false,
    1,
    'ce-compound',
    'approved'
  ),
  (
    'seed_ce-debug',
    'ce-debug',
    'ce-debug',
    'agent-methodology',
    'EveryInc',
    'Every Inc.',
    'Every Inc.',
    5.0,
    0,
    'Finder rodårsager og retter fejl gennem systematisk reproduktion, hypotesetest og præcis isolering af problemets oprindelse.',
    'Systematically find root causes and fix bugs using hypothesis-driven debugging loops.',
    ARRAY['claude-code', 'compound-engineering', 'debugging', 'testing'],
    'https://github.com/EveryInc/compound-engineering-plugin/tree/main/plugins/compound-engineering/skills/ce-debug',
    false,
    false,
    1,
    'ce-debug',
    'approved'
  ),
  (
    'seed_ce-code-review',
    'ce-code-review',
    'ce-code-review',
    'fullstack-devops',
    'EveryInc',
    'Every Inc.',
    'Every Inc.',
    5.0,
    0,
    'Udfører struktureret kodereview med specialiserede personas, konfidensvurdering af fund og verificerede rettelser før merge.',
    'Structured code review using tiered persona agents, confidence-gated findings, and verified fixes.',
    ARRAY['claude-code', 'compound-engineering', 'code-review', 'git'],
    'https://github.com/EveryInc/compound-engineering-plugin/tree/main/plugins/compound-engineering/skills/ce-code-review',
    false,
    false,
    1,
    'ce-code-review',
    'approved'
  ),
  (
    'seed_ce-worktree',
    'ce-worktree',
    'ce-worktree',
    'agent-methodology',
    'EveryInc',
    'Every Inc.',
    'Every Inc.',
    5.0,
    0,
    'Isolerer agentens kodeændringer i separate git worktrees, så udvikling kan ske parallelt uden at forstyrre den aktive arbejdsgren.',
    'Ensure agent work happens in isolated git worktrees without disturbing the current checkout.',
    ARRAY['claude-code', 'compound-engineering', 'git', 'worktree'],
    'https://github.com/EveryInc/compound-engineering-plugin/tree/main/plugins/compound-engineering/skills/ce-worktree',
    false,
    false,
    1,
    'ce-worktree',
    'approved'
  ),
  (
    'seed_ce-simplify-code',
    'ce-simplify-code',
    'ce-simplify-code',
    'agent-methodology',
    'EveryInc',
    'Every Inc.',
    'Every Inc.',
    5.0,
    0,
    'Forenkler og opstrammer nyligt ændret kildekode med fokus på øget læsbarhed, genbrug og færre linjer uden at ændre adfærd.',
    'Simplify and refine recently changed code for clarity, reuse, quality, and efficiency while preserving behavior.',
    ARRAY['claude-code', 'compound-engineering', 'refactoring', 'clean-code'],
    'https://github.com/EveryInc/compound-engineering-plugin/tree/main/plugins/compound-engineering/skills/ce-simplify-code',
    false,
    false,
    1,
    'ce-simplify-code',
    'approved'
  )
ON CONFLICT (id) DO UPDATE SET
  title_da = EXCLUDED.title_da,
  title_en = EXCLUDED.title_en,
  category = EXCLUDED.category,
  vibe_coder = EXCLUDED.vibe_coder,
  vibe_coder_title_da = EXCLUDED.vibe_coder_title_da,
  vibe_coder_title_en = EXCLUDED.vibe_coder_title_en,
  description_da = EXCLUDED.description_da,
  description_en = EXCLUDED.description_en,
  tags = EXCLUDED.tags,
  github_url = EXCLUDED.github_url,
  slug = EXCLUDED.slug,
  review_state = EXCLUDED.review_state;
