-- ============================================================================
-- LAUNCH CONTENT SNAPSHOT — TEMPORARY, MEANT TO BE REPLACED.
-- ============================================================================
-- A one-time snapshot of public, mostly open-source skills copied from
-- skills.sh (https://www.skills.sh/topic) to remove the placeholder feel at
-- launch. This is NOT original content and is not load-bearing: over time the
-- catalog is rebuilt by the community via the submit flow. Each row carries a
-- `source` (the upstream repo) for attribution.
--
-- Danish text mirrors English for now (the *_da columns exist); a localization
-- pass replaces the mirror later. To revise the snapshot, edit this file —
-- it is the single, declarative seed. ON CONFLICT DO NOTHING keeps re-runs and
-- community edits safe (seed ids are prefixed `seed_`).
--
-- hot_rank / trending_rank below are a hand-curated launch ordering across this
-- catalog (anchored on entries that actually appear on skills.sh's boards, e.g.
-- find-skills, agent-browser). The own-signal engine replaces them in Phase 4.
-- ============================================================================

insert into public.skills
  (id, category, vibe_coder, vibe_coder_title_da, vibe_coder_title_en,
   title_da, title_en, description_da, description_en, tags, github_url, source,
   hot_rank, trending_rank)
values
  -- Frontend & React -------------------------------------------------------
  ('seed_vercel-react-best-practices', 'frontend-react', 'vercel-labs', 'skills.sh bidragyder', 'skills.sh contributor', 'vercel-react-best-practices', 'vercel-react-best-practices', '69 prioritized React performance rules covering waterfalls, bundle size, re-renders, and advanced patterns', '69 prioritized React performance rules covering waterfalls, bundle size, re-renders, and advanced patterns', ARRAY['skills.sh','react'], 'https://github.com/vercel-labs/agent-skills', 'https://github.com/vercel-labs/agent-skills', 3, NULL),
  ('seed_vercel-composition-patterns', 'frontend-react', 'vercel-labs', 'skills.sh bidragyder', 'skills.sh contributor', 'vercel-composition-patterns', 'vercel-composition-patterns', 'Compound components, render props, and context patterns for scalable component APIs', 'Compound components, render props, and context patterns for scalable component APIs', ARRAY['skills.sh','react'], 'https://github.com/vercel-labs/agent-skills', 'https://github.com/vercel-labs/agent-skills', NULL, NULL),
  ('seed_shadcn', 'frontend-react', 'shadcn', 'skills.sh bidragyder', 'skills.sh contributor', 'shadcn', 'shadcn', 'shadcn/ui component usage, customization, and Tailwind integration', 'shadcn/ui component usage, customization, and Tailwind integration', ARRAY['skills.sh','react'], 'https://github.com/shadcn/ui', 'https://github.com/shadcn/ui', 2, NULL),
  ('seed_typescript-advanced-types', 'frontend-react', 'wshobson', 'skills.sh bidragyder', 'skills.sh contributor', 'typescript-advanced-types', 'typescript-advanced-types', 'Discriminated unions, conditional types, template literals, and utility type patterns', 'Discriminated unions, conditional types, template literals, and utility type patterns', ARRAY['skills.sh','typescript'], 'https://github.com/wshobson/agents', 'https://github.com/wshobson/agents', NULL, NULL),
  ('seed_tailwind-design-system', 'frontend-react', 'wshobson', 'skills.sh bidragyder', 'skills.sh contributor', 'tailwind-design-system', 'tailwind-design-system', 'Design system implementation with Tailwind: tokens, variants, and component patterns', 'Design system implementation with Tailwind: tokens, variants, and component patterns', ARRAY['skills.sh','tailwind'], 'https://github.com/wshobson/agents', 'https://github.com/wshobson/agents', NULL, NULL),

  -- Next.js ----------------------------------------------------------------
  ('seed_next-best-practices', 'nextjs', 'vercel-labs', 'skills.sh bidragyder', 'skills.sh contributor', 'next-best-practices', 'next-best-practices', 'File conventions, RSC boundaries, data patterns, async APIs, and metadata', 'File conventions, RSC boundaries, data patterns, async APIs, and metadata', ARRAY['skills.sh','nextjs'], 'https://github.com/vercel-labs/next-skills', 'https://github.com/vercel-labs/next-skills', 6, NULL),
  ('seed_deploy-to-vercel', 'nextjs', 'vercel-labs', 'skills.sh bidragyder', 'skills.sh contributor', 'deploy-to-vercel', 'deploy-to-vercel', 'Deploy Next.js apps to Vercel with correct config and environment setup', 'Deploy Next.js apps to Vercel with correct config and environment setup', ARRAY['skills.sh','nextjs','vercel'], 'https://github.com/vercel-labs/agent-skills', 'https://github.com/vercel-labs/agent-skills', NULL, NULL),
  ('seed_next-cache-components', 'nextjs', 'vercel-labs', 'skills.sh bidragyder', 'skills.sh contributor', 'next-cache-components', 'next-cache-components', 'PPR, use cache directive, cacheLife, cacheTag, and revalidateTag', 'PPR, use cache directive, cacheLife, cacheTag, and revalidateTag', ARRAY['skills.sh','nextjs'], 'https://github.com/vercel-labs/next-skills', 'https://github.com/vercel-labs/next-skills', NULL, 1),
  ('seed_turborepo', 'nextjs', 'vercel', 'skills.sh bidragyder', 'skills.sh contributor', 'turborepo', 'turborepo', 'Turborepo task pipelines, caching, remote cache, and CI configuration', 'Turborepo task pipelines, caching, remote cache, and CI configuration', ARRAY['skills.sh','monorepo'], 'https://github.com/vercel/turborepo', 'https://github.com/vercel/turborepo', NULL, NULL),
  ('seed_ai-sdk', 'nextjs', 'vercel', 'skills.sh bidragyder', 'skills.sh contributor', 'ai-sdk', 'ai-sdk', 'Vercel AI SDK: generateText, streamText, tool calling, and useChat', 'Vercel AI SDK: generateText, streamText, tool calling, and useChat', ARRAY['skills.sh','ai'], 'https://github.com/vercel/ai', 'https://github.com/vercel/ai', NULL, 2),

  -- Design & UI ------------------------------------------------------------
  ('seed_frontend-design', 'design-ui', 'anthropics', 'skills.sh bidragyder', 'skills.sh contributor', 'frontend-design', 'frontend-design', 'Comprehensive frontend design patterns and visual polish guidance', 'Comprehensive frontend design patterns and visual polish guidance', ARRAY['skills.sh','design'], 'https://github.com/anthropics/skills', 'https://github.com/anthropics/skills', 8, NULL),
  ('seed_web-design-guidelines', 'design-ui', 'vercel-labs', 'skills.sh bidragyder', 'skills.sh contributor', 'web-design-guidelines', 'web-design-guidelines', 'Vercel''s Web Interface Guidelines covering spacing, typography, interaction, and accessibility', 'Vercel''s Web Interface Guidelines covering spacing, typography, interaction, and accessibility', ARRAY['skills.sh','design'], 'https://github.com/vercel-labs/agent-skills', 'https://github.com/vercel-labs/agent-skills', NULL, NULL),
  ('seed_ui-ux-pro-max', 'design-ui', 'nextlevelbuilder', 'skills.sh bidragyder', 'skills.sh contributor', 'ui-ux-pro-max', 'ui-ux-pro-max', 'Advanced UI/UX patterns for complex interfaces and interaction design', 'Advanced UI/UX patterns for complex interfaces and interaction design', ARRAY['skills.sh','design'], 'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill', 'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill', NULL, 6),
  ('seed_canvas-design', 'design-ui', 'anthropics', 'skills.sh bidragyder', 'skills.sh contributor', 'canvas-design', 'canvas-design', 'Design generation and iteration in canvas-based environments', 'Design generation and iteration in canvas-based environments', ARRAY['skills.sh','design'], 'https://github.com/anthropics/skills', 'https://github.com/anthropics/skills', NULL, NULL),
  ('seed_polish', 'design-ui', 'pbakaus', 'skills.sh bidragyder', 'skills.sh contributor', 'polish', 'polish', 'Final-pass visual refinement: tighten spacing, sharpen type, clean edges', 'Final-pass visual refinement: tighten spacing, sharpen type, clean edges', ARRAY['skills.sh','design'], 'https://github.com/pbakaus/impeccable', 'https://github.com/pbakaus/impeccable', NULL, NULL),
  ('seed_delight', 'design-ui', 'pbakaus', 'skills.sh bidragyder', 'skills.sh contributor', 'delight', 'delight', 'Add micro-interactions and motion that make interfaces feel alive', 'Add micro-interactions and motion that make interfaces feel alive', ARRAY['skills.sh','design','motion'], 'https://github.com/pbakaus/impeccable', 'https://github.com/pbakaus/impeccable', NULL, NULL),
  ('seed_extract-design-system', 'design-ui', 'arvindrk', 'skills.sh bidragyder', 'skills.sh contributor', 'extract-design-system', 'extract-design-system', 'Extract tokens, components, and patterns from existing codebases', 'Extract tokens, components, and patterns from existing codebases', ARRAY['skills.sh','design'], 'https://github.com/arvindrk/extract-design-system', 'https://github.com/arvindrk/extract-design-system', NULL, NULL),
  ('seed_emil-design-eng', 'design-ui', 'emilkowalski', 'skills.sh bidragyder', 'skills.sh contributor', 'emil-design-eng', 'emil-design-eng', 'Emil Kowalski''s design engineering principles covering motion, detail, and craftsmanship', 'Emil Kowalski''s design engineering principles covering motion, detail, and craftsmanship', ARRAY['skills.sh','design'], 'https://github.com/emilkowalski/skill', 'https://github.com/emilkowalski/skill', NULL, NULL),

  -- Mobile -----------------------------------------------------------------
  ('seed_vercel-react-native-skills', 'mobile', 'vercel-labs', 'skills.sh bidragyder', 'skills.sh contributor', 'vercel-react-native-skills', 'vercel-react-native-skills', 'React Native best practices: performance, navigation, native modules, and platform APIs', 'React Native best practices: performance, navigation, native modules, and platform APIs', ARRAY['skills.sh','mobile','react-native'], 'https://github.com/vercel-labs/agent-skills', 'https://github.com/vercel-labs/agent-skills', NULL, 5),
  ('seed_sleek-design-mobile-apps', 'mobile', 'sleekdotdesign', 'skills.sh bidragyder', 'skills.sh contributor', 'sleek-design-mobile-apps', 'sleek-design-mobile-apps', 'Mobile-first design patterns for iOS and Android: gestures, safe areas, and native feel', 'Mobile-first design patterns for iOS and Android: gestures, safe areas, and native feel', ARRAY['skills.sh','mobile','design'], 'https://github.com/sleekdotdesign/agent-skills', 'https://github.com/sleekdotdesign/agent-skills', NULL, NULL),
  ('seed_building-native-ui', 'mobile', 'expo', 'skills.sh bidragyder', 'skills.sh contributor', 'building-native-ui', 'building-native-ui', 'Expo native UI components: lists, modals, tabs, bottom sheets, and haptics', 'Expo native UI components: lists, modals, tabs, bottom sheets, and haptics', ARRAY['skills.sh','mobile','expo'], 'https://github.com/expo/skills', 'https://github.com/expo/skills', NULL, NULL),
  ('seed_native-data-fetching', 'mobile', 'expo', 'skills.sh bidragyder', 'skills.sh contributor', 'native-data-fetching', 'native-data-fetching', 'Data fetching for native apps: offline caching, background refresh, and sync patterns', 'Data fetching for native apps: offline caching, background refresh, and sync patterns', ARRAY['skills.sh','mobile','expo'], 'https://github.com/expo/skills', 'https://github.com/expo/skills', NULL, NULL),
  ('seed_expo-tailwind-setup', 'mobile', 'expo', 'skills.sh bidragyder', 'skills.sh contributor', 'expo-tailwind-setup', 'expo-tailwind-setup', 'NativeWind and Tailwind setup in Expo with correct native class handling', 'NativeWind and Tailwind setup in Expo with correct native class handling', ARRAY['skills.sh','mobile','expo'], 'https://github.com/expo/skills', 'https://github.com/expo/skills', NULL, NULL),
  ('seed_upgrading-expo', 'mobile', 'expo', 'skills.sh bidragyder', 'skills.sh contributor', 'upgrading-expo', 'upgrading-expo', 'Expo SDK upgrade guide covering breaking changes, native module compatibility, and migration steps', 'Expo SDK upgrade guide covering breaking changes, native module compatibility, and migration steps', ARRAY['skills.sh','mobile','expo'], 'https://github.com/expo/skills', 'https://github.com/expo/skills', NULL, NULL),

  -- Agent workflows --------------------------------------------------------
  ('seed_find-skills', 'agent-workflows', 'vercel-labs', 'skills.sh bidragyder', 'skills.sh contributor', 'find-skills', 'find-skills', 'Discover and install skills from skills.sh directly inside an agent session', 'Discover and install skills from skills.sh directly inside an agent session', ARRAY['skills.sh','agents'], 'https://github.com/vercel-labs/skills', 'https://github.com/vercel-labs/skills', 1, NULL),
  ('seed_agent-browser', 'agent-workflows', 'vercel-labs', 'skills.sh bidragyder', 'skills.sh contributor', 'agent-browser', 'agent-browser', 'Full browser automation: navigate, click, fill forms, extract data, and screenshot', 'Full browser automation: navigate, click, fill forms, extract data, and screenshot', ARRAY['skills.sh','agents','browser'], 'https://github.com/vercel-labs/agent-browser', 'https://github.com/vercel-labs/agent-browser', 5, NULL),
  ('seed_skill-creator', 'agent-workflows', 'anthropics', 'skills.sh bidragyder', 'skills.sh contributor', 'skill-creator', 'skill-creator', 'Create, test, and publish new skills from within your agent', 'Create, test, and publish new skills from within your agent', ARRAY['skills.sh','agents'], 'https://github.com/anthropics/skills', 'https://github.com/anthropics/skills', NULL, NULL),
  ('seed_brainstorming', 'agent-workflows', 'obra', 'skills.sh bidragyder', 'skills.sh contributor', 'brainstorming', 'brainstorming', 'Structured ideation and problem decomposition frameworks', 'Structured ideation and problem decomposition frameworks', ARRAY['skills.sh','agents'], 'https://github.com/obra/superpowers', 'https://github.com/obra/superpowers', NULL, NULL),
  ('seed_systematic-debugging', 'agent-workflows', 'obra', 'skills.sh bidragyder', 'skills.sh contributor', 'systematic-debugging', 'systematic-debugging', 'Hypothesis-driven debugging loop: observe, hypothesize, test, verify', 'Hypothesis-driven debugging loop: observe, hypothesize, test, verify', ARRAY['skills.sh','agents','debugging'], 'https://github.com/obra/superpowers', 'https://github.com/obra/superpowers', NULL, 8),
  ('seed_writing-plans', 'agent-workflows', 'obra', 'skills.sh bidragyder', 'skills.sh contributor', 'writing-plans', 'writing-plans', 'Write structured implementation plans before starting complex tasks', 'Write structured implementation plans before starting complex tasks', ARRAY['skills.sh','agents','planning'], 'https://github.com/obra/superpowers', 'https://github.com/obra/superpowers', NULL, NULL),
  ('seed_subagent-driven-development', 'agent-workflows', 'obra', 'skills.sh bidragyder', 'skills.sh contributor', 'subagent-driven-development', 'subagent-driven-development', 'Orchestrate specialized subagents for different task components', 'Orchestrate specialized subagents for different task components', ARRAY['skills.sh','agents'], 'https://github.com/obra/superpowers', 'https://github.com/obra/superpowers', NULL, NULL),
  ('seed_using-git-worktrees', 'agent-workflows', 'obra', 'skills.sh bidragyder', 'skills.sh contributor', 'using-git-worktrees', 'using-git-worktrees', 'Use git worktrees to run parallel agent sessions on separate branches', 'Use git worktrees to run parallel agent sessions on separate branches', ARRAY['skills.sh','agents','git'], 'https://github.com/obra/superpowers', 'https://github.com/obra/superpowers', NULL, NULL),

  -- Database ---------------------------------------------------------------
  ('seed_supabase-postgres-best-practices', 'database', 'supabase', 'skills.sh bidragyder', 'skills.sh contributor', 'supabase-postgres-best-practices', 'supabase-postgres-best-practices', 'Postgres patterns for Supabase: schema design, RLS, indexing, and query performance', 'Postgres patterns for Supabase: schema design, RLS, indexing, and query performance', ARRAY['skills.sh','database','postgres'], 'https://github.com/supabase/agent-skills', 'https://github.com/supabase/agent-skills', NULL, NULL),
  ('seed_supabase', 'database', 'supabase', 'skills.sh bidragyder', 'skills.sh contributor', 'supabase', 'supabase', 'Supabase client: auth, storage, realtime, edge functions, and migrations', 'Supabase client: auth, storage, realtime, edge functions, and migrations', ARRAY['skills.sh','database','supabase'], 'https://github.com/supabase/agent-skills', 'https://github.com/supabase/agent-skills', 4, NULL),
  ('seed_firebase-basics', 'database', 'firebase', 'skills.sh bidragyder', 'skills.sh contributor', 'firebase-basics', 'firebase-basics', 'Firebase setup, Firestore queries, security rules, and project configuration', 'Firebase setup, Firestore queries, security rules, and project configuration', ARRAY['skills.sh','database','firebase'], 'https://github.com/firebase/agent-skills', 'https://github.com/firebase/agent-skills', NULL, NULL),
  ('seed_convex-quickstart', 'database', 'get-convex', 'skills.sh bidragyder', 'skills.sh contributor', 'convex-quickstart', 'convex-quickstart', 'Convex schema, queries, mutations, and real-time reactivity patterns', 'Convex schema, queries, mutations, and real-time reactivity patterns', ARRAY['skills.sh','database','convex'], 'https://github.com/get-convex/agent-skills', 'https://github.com/get-convex/agent-skills', NULL, 3),
  ('seed_neon-postgres', 'database', 'neondatabase', 'skills.sh bidragyder', 'skills.sh contributor', 'neon-postgres', 'neon-postgres', 'Neon-specific patterns: branching workflow, serverless driver, and connection pooling', 'Neon-specific patterns: branching workflow, serverless driver, and connection pooling', ARRAY['skills.sh','database','postgres'], 'https://github.com/neondatabase/agent-skills', 'https://github.com/neondatabase/agent-skills', NULL, NULL),
  ('seed_turso-db', 'database', 'tursodatabase', 'skills.sh bidragyder', 'skills.sh contributor', 'turso-db', 'turso-db', 'Turso (libSQL): edge-replicated SQLite — setup, queries, and replication patterns for serverless apps', 'Turso (libSQL): edge-replicated SQLite — setup, queries, and replication patterns for serverless apps', ARRAY['skills.sh','database','sqlite'], 'https://github.com/tursodatabase/agent-skills', 'https://github.com/tursodatabase/agent-skills', NULL, 4),
  ('seed_drizzle-orm', 'database', 'bobmatnyc', 'skills.sh bidragyder', 'skills.sh contributor', 'drizzle-orm', 'drizzle-orm', 'Drizzle ORM: type-safe schemas, migrations, and queries with end-to-end TypeScript inference', 'Drizzle ORM: type-safe schemas, migrations, and queries with end-to-end TypeScript inference', ARRAY['skills.sh','database','orm'], 'https://github.com/bobmatnyc/claude-mpm-skills', 'https://github.com/bobmatnyc/claude-mpm-skills', NULL, NULL),
  ('seed_duckdb-query', 'database', 'duckdb', 'skills.sh bidragyder', 'skills.sh contributor', 'duckdb-query', 'duckdb-query', 'DuckDB query patterns for in-process analytical workloads, Parquet/CSV reads, and embedded analytics', 'DuckDB query patterns for in-process analytical workloads, Parquet/CSV reads, and embedded analytics', ARRAY['skills.sh','database','analytics'], 'https://github.com/duckdb/duckdb-skills', 'https://github.com/duckdb/duckdb-skills', NULL, NULL),

  -- Testing ----------------------------------------------------------------
  ('seed_test-driven-development', 'testing', 'obra', 'skills.sh bidragyder', 'skills.sh contributor', 'test-driven-development', 'test-driven-development', 'TDD loop: write the failing test first, implement the minimal change, verify, then refactor', 'TDD loop: write the failing test first, implement the minimal change, verify, then refactor', ARRAY['skills.sh','testing','tdd'], 'https://github.com/obra/superpowers', 'https://github.com/obra/superpowers', 7, NULL),
  ('seed_webapp-testing', 'testing', 'anthropics', 'skills.sh bidragyder', 'skills.sh contributor', 'webapp-testing', 'webapp-testing', 'Web app testing patterns covering unit, integration, and end-to-end approaches', 'Web app testing patterns covering unit, integration, and end-to-end approaches', ARRAY['skills.sh','testing'], 'https://github.com/anthropics/skills', 'https://github.com/anthropics/skills', NULL, NULL),
  ('seed_verification-before-completion', 'testing', 'obra', 'skills.sh bidragyder', 'skills.sh contributor', 'verification-before-completion', 'verification-before-completion', 'Force a verification pass before any task is marked done', 'Force a verification pass before any task is marked done', ARRAY['skills.sh','testing'], 'https://github.com/obra/superpowers', 'https://github.com/obra/superpowers', NULL, NULL),
  ('seed_playwright-best-practices', 'testing', 'currents-dev', 'skills.sh bidragyder', 'skills.sh contributor', 'playwright-best-practices', 'playwright-best-practices', 'Playwright patterns: selectors, fixtures, parallelism, and CI integration', 'Playwright patterns: selectors, fixtures, parallelism, and CI integration', ARRAY['skills.sh','testing','playwright'], 'https://github.com/currents-dev/playwright-best-practices-skill', 'https://github.com/currents-dev/playwright-best-practices-skill', NULL, 7),
  ('seed_playwright-cli', 'testing', 'microsoft', 'skills.sh bidragyder', 'skills.sh contributor', 'playwright-cli', 'playwright-cli', 'Control a live browser via the Playwright CLI to record, inspect, and replay interactions', 'Control a live browser via the Playwright CLI to record, inspect, and replay interactions', ARRAY['skills.sh','testing','playwright'], 'https://github.com/microsoft/playwright-cli', 'https://github.com/microsoft/playwright-cli', NULL, NULL),

  -- Marketing --------------------------------------------------------------
  ('seed_seo-audit', 'marketing', 'coreyhaines31', 'skills.sh bidragyder', 'skills.sh contributor', 'seo-audit', 'seo-audit', 'Technical and on-page SEO audit with prioritized action plan', 'Technical and on-page SEO audit with prioritized action plan', ARRAY['skills.sh','marketing','seo'], 'https://github.com/coreyhaines31/marketingskills', 'https://github.com/coreyhaines31/marketingskills', NULL, NULL),
  ('seed_copywriting', 'marketing', 'coreyhaines31', 'skills.sh bidragyder', 'skills.sh contributor', 'copywriting', 'copywriting', 'Persuasive copy across formats: headlines, landing pages, email, and ads', 'Persuasive copy across formats: headlines, landing pages, email, and ads', ARRAY['skills.sh','marketing','copy'], 'https://github.com/coreyhaines31/marketingskills', 'https://github.com/coreyhaines31/marketingskills', NULL, NULL),
  ('seed_marketing-psychology', 'marketing', 'coreyhaines31', 'skills.sh bidragyder', 'skills.sh contributor', 'marketing-psychology', 'marketing-psychology', 'Behavioral principles applied to messaging, design, and conversion flows', 'Behavioral principles applied to messaging, design, and conversion flows', ARRAY['skills.sh','marketing'], 'https://github.com/coreyhaines31/marketingskills', 'https://github.com/coreyhaines31/marketingskills', NULL, NULL),
  ('seed_content-strategy', 'marketing', 'coreyhaines31', 'skills.sh bidragyder', 'skills.sh contributor', 'content-strategy', 'content-strategy', 'Topic planning, content calendars, and editorial frameworks', 'Topic planning, content calendars, and editorial frameworks', ARRAY['skills.sh','marketing','content'], 'https://github.com/coreyhaines31/marketingskills', 'https://github.com/coreyhaines31/marketingskills', NULL, NULL),
  ('seed_programmatic-seo', 'marketing', 'coreyhaines31', 'skills.sh bidragyder', 'skills.sh contributor', 'programmatic-seo', 'programmatic-seo', 'Large-scale SEO content programs built for consistent quality at volume', 'Large-scale SEO content programs built for consistent quality at volume', ARRAY['skills.sh','marketing','seo'], 'https://github.com/coreyhaines31/marketingskills', 'https://github.com/coreyhaines31/marketingskills', NULL, NULL),
  ('seed_pricing-strategy', 'marketing', 'coreyhaines31', 'skills.sh bidragyder', 'skills.sh contributor', 'pricing-strategy', 'pricing-strategy', 'Pricing page structure, plan naming, anchoring, and conversion optimization', 'Pricing page structure, plan naming, anchoring, and conversion optimization', ARRAY['skills.sh','marketing'], 'https://github.com/coreyhaines31/marketingskills', 'https://github.com/coreyhaines31/marketingskills', NULL, NULL),
  ('seed_launch-strategy', 'marketing', 'coreyhaines31', 'skills.sh bidragyder', 'skills.sh contributor', 'launch-strategy', 'launch-strategy', 'Go-to-market planning, channel sequencing, and launch execution', 'Go-to-market planning, channel sequencing, and launch execution', ARRAY['skills.sh','marketing','launch'], 'https://github.com/coreyhaines31/marketingskills', 'https://github.com/coreyhaines31/marketingskills', NULL, NULL),
  ('seed_ai-seo', 'marketing', 'coreyhaines31', 'skills.sh bidragyder', 'skills.sh contributor', 'ai-seo', 'ai-seo', 'Optimize content for AI Overviews, Perplexity, and answer engine visibility', 'Optimize content for AI Overviews, Perplexity, and answer engine visibility', ARRAY['skills.sh','marketing','seo'], 'https://github.com/coreyhaines31/marketingskills', 'https://github.com/coreyhaines31/marketingskills', NULL, NULL)
on conflict (id) do nothing;
